# Generated by Django 5.2.1 on 2025-05-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('CLOSED', 'Fechada')], default='OPEN', max_length=10, verbose_name='Estado')),
                ('created_event_timestamp', models.DateTimeField(verbose_name='Timestamp do Evento de Criação')),
                ('db_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado no DB em')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-db_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('event_timestamp', models.DateTimeField(verbose_name='Timestamp do Evento')),
                ('direction', models.CharField(choices=[('SENT', 'Enviada'), ('RECEIVED', 'Recebida')], max_length=10, verbose_name='Direção')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('db_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado no DB em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['event_timestamp'],
            },
        ),
    ]
